CREATE TABLE IF NOT EXISTS TODO (
    TODO_ID bigint NOT NULL AUTO_INCREMENT,
    CONTENT varchar(100) NOT NULL,
    TODO_STATUS varchar(20) NOT NULL,
    CREATED_AT datetime NOT NULL,
    PRIMARY KEY (TODO_ID)
);